Vagrant.configure(2) do |config|
  config.vm.box = "ss-vagrant-v1.11.0"
  config.vm.box_url = "https://github.com/shirasagi/ss-vagrant/releases/download/ss-vagrant-v1.11.0/ss-vagrant-virtualbox-x86_64.box"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
end
