Vagrant.configure(2) do |config|
  config.vm.box = "shirasagi/shirasagi"
  config.vm.box_version = "1.16.1"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
